site_name: BunkerWeb documentation
site_url: https://docs.bunkerweb.io/
repo_url: https://github.com/bunkerity/bunkerweb
site_description: Documentation of BunkerWeb, the open source and next generation WAF.
copyright: Copyright &copy; <script>document.write(new Date().getFullYear())</script> Bunkerity

nav: # language-agnostic structure (same file names in each locale folder)
  - Introduction: "index.md"
  - Concepts: "concepts.md"
  - Integrations: "integrations.md"
  - Quickstart guide: "quickstart-guide.md"
  - Features: "features.md"
  - Advanced usages: "advanced.md"
  - Web UI: "web-ui.md"
  - Upgrading: "upgrading.md"
  - Troubleshooting: "troubleshooting.md"
  - Plugins: "plugins.md"
  - Professional services: "professional-services.md"
  - About: "about.md"

theme:
  name: material
  language: en
  logo: assets/logo.png
  favicon: assets/favicon.png
  font: false
  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.integrate
    - content.code.copy
  custom_dir: docs/overrides

extra_css:
  - assets/extra.css

extra_javascript:
  - assets/extra.js
  - https://chatbot.bunkerweb.io/static/js/chatbot.js

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - tables
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra:
  version:
    provider: mike
    version: latest
  generator: false
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.com/invite/fTf46FmtyD
    - icon: fontawesome/brands/github
      link: https://github.com/bunkerity
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/bunkerity/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/bunkerity

plugins:
  - search
  - social:
      cards_layout_options:
        background_color: "#0b5577"
        color: "white"
  - mike:
      canonical_version: latest
  - print-site
  - i18n:
      docs_structure: folder
      languages:
        - locale: en
          name: English
          build: true
          default: true
          site_name: BunkerWeb documentation
        - locale: fr
          name: Français
          build: true
          site_name: Documentation BunkerWeb
          nav_translations:
            Introduction: Introduction
            Concepts: Concepts
            Integrations: Intégrations
            "Quickstart guide": "Guide de démarrage rapide"
            Features: Fonctionnalités
            "Advanced usages": "Utilisations avancées"
            "Web UI": "Interface Web"
            Upgrading: "Mise à niveau"
            Troubleshooting: Dépannage
            Plugins: Plugins
            "Professional services": "Services professionnels"
            About: "À propos"
        - locale: de
          name: Deutsch
          build: true
          site_name: BunkerWeb Dokumentation
          nav_translations:
            Introduction: Einführung
            Concepts: Konzepte
            Integrations: Integrationen
            "Quickstart guide": Schnellstart
            Features: Funktionen
            "Advanced usages": "Erweiterte Nutzung"
            "Web UI": "Weboberfläche"
            Upgrading: Aktualisierung
            Troubleshooting: Fehlerbehebung
            Plugins: Plugins
            "Professional services": "Professionelle Dienste"
            About: Über
        - locale: es
          name: Español
          build: true
          site_name: Documentación de BunkerWeb
          nav_translations:
            Introduction: Introducción
            Concepts: Conceptos
            Integrations: Integraciones
            "Quickstart guide": "Guía de inicio rápido"
            Features: Funcionalidades
            "Advanced usages": "Usos avanzados"
            "Web UI": "Interfaz web"
            Upgrading: Actualización
            Troubleshooting: "Solución de problemas"
            Plugins: Plugins
            "Professional services": "Servicios profesionales"
            About: "Acerca de"
